swagger: '2.0'
info:
  version: latest
  title: IAM API - Basic Operations
host: s3.seagate.com
schemes:
  - http
  - https
paths:
  '/':
    post:
      tags:
        - Change Password
      parameters:
        - name: Action
          in: query
          type: string
          required: true
        - name: Version
          in: query
          type: string
          required: false
        - name: OldPassword
          in: query
          type: string
          required: true
        - name: NewPassword
          in: query
          type: string
          required: true
        - name: content-type
          in: header
          type: string
          required: true
        - name: user-agent
          in: header
          type: string
          required: true
        - name: x-amz-date
          in: header
          type: string
          required: true
        - name: Authorization
          in: header
          type: string
          required: true
        - name: SignedHeaders
          in: header
          type: string
          required: true
        - name: Signature
          in: header
          type: string
          required: true
        - name: content-length
          in: header
          type: string
          required: true
      produces:
        - application/xml
      responses:
        '200':
          description: OK
          schema:
            type: object
            xml:
              name: ChangePasswordResponse
            properties:
              ResponseMetadata:
                    type: object
                    properties:
                      RequestId:
                        type: string
          headers:
            Content-Type:
              type: string
            Content-length:
              type: integer
            connection:
              type: string
    