swagger: '2.0'
info:
  version: latest
  title: IAM API - Basic Operations
host: s3.seagate.com
schemes:
  - http
  - https
paths:
  '/':
    post:
      tags:
        - Get Temporary Auth Credentials
      parameters:
        - name: Action
          in: query
          type: string
          required: true
        - name: Account-Name
          in: query
          description: Password
          type: string
          required: true
        - name: content-type
          in: header
          type: string
          required: true
        - name: Accept
          in: header
          type: string
          required: true
        - name: Authorization
          in: header
          description: >-
            This Header contains credentials to authorize a User-Agent with
            server.
          type: string
          required: true
        - name: SignedHeaders
          in: header
          type: string
          required: true
        - name: Signature
          in: header
          type: string
          required: true
        - name: x-amz-date
          in: header
          type: string
          required: true
      produces:
        - application/xml
      responses:
        '201':
          description: OK
          schema:
            type: object
            xml:
              name: GetTempAuthCredentialsResponse
            properties:
              GetTempAuthCredentialsResult:
                type: object
                properties:
                  AccessKey:
                    type: object
                    properties:
                      UserName:
                        type: string
                      AccessKeyId:
                        type: string
                      Status:
                        type: string
                      SecretAccessKey:
                        type: string
                      ExpiryTime:
                        type: string
                      SessionToken:
                        type: string
              ResponseMetadata:
                type: object
                properties:
                  RequestId:
                    type: string
          headers:
            Content-Type:
              type: string
            Content-length:
              type: integer
            connection:
              type: string
    