swagger: '2.0'
info:
  version: latest
  title: IAM API - Basic Operations
host: s3.seagate.com
schemes:
  - http
  - https
paths:
  '/':
    post:
      tags:
        - List Users
      parameters:
        - name: Action
          in: query
          type: string
          required: true
        - name: version
          in: query
          type: string
          required: false
        - name: content-type
          in: header
          type: string
          required: true
        - name: user-agent
          in: header
          type: string
          required: true
        - name: Authorization
          in: header
          description: >-
            This Header contains credentials to authorize a User-Agent with
            server.
          type: string
          required: true
        - name: SignedHeaders
          in: header
          type: string
          required: true
        - name: Signature
          in: header
          type: string
          required: true
        - name: x-amz-date
          in: header
          type: string
          required: true
        - name: content-length
          in: header
          type: string
          required: true
      produces:
        - application/xml
      responses:
        '200':
          description: OK
          schema:
            type: object
            xml:
              name: ListUsersResponse
            properties:
              ListUsersResult:
                type: object
                properties:
                  Users:
                    type: object
                    properties:
                      member:
                        type: object
                        properties:
                          userId:
                            type: string
                          path:
                            type: string
                          username:
                            type: string
                          arn:
                            type: string
                          CreateDate:
                            type: string
                  IsTruncated:
                    type: boolean
              ResponseMetadata:
                type: object
                properties:
                  RequestId:
                    type: string
          headers:
            Content-Type:
              type: string
            Content-length:
              type: integer
            connection:
              type: string
    